api:
    isEnabled: true
    mode: debug # debug, release or test
    host: 0.0.0.0
    port: 8080

mssql:
  server: yourserver-sql.database.windows.net
  port: 1433
  user: sqladmin
  password: password@123
  database: p2